<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create super admin role
        $superAdminRole = Role::firstOrCreate(
            ['name' => 'superadmin', 'guard_name' => 'web'],
            [
                'label' => 'Super Admin',
                'description' => 'Super Admin has full access to all features',
                'created_by' => null,
            ]
        );

        // Create admin role
        $adminRole = Role::firstOrCreate(
            ['name' => 'company', 'guard_name' => 'web'],
            [
                'label' => 'Company',
                'description' => 'Company has access to manage buissness',
                'created_by' => null,
            ]
        );

        // Get all permissions
        $permissions = Permission::all();

        // Assign all permissions to super admin
        $superAdminRole->syncPermissions($permissions);

        // Assign specific permissions to company role
        $adminPermissions = Permission::whereIn('name', [
            'manage-dashboard',
            'view-dashboard',
            'manage-users',
            'create-users',
            'edit-users',
            'delete-users',
            'view-users',
            'reset-password-users',
            'toggle-status-users',

            // Branch management permissions
            'manage-branches',
            'view-branches',
            'create-branches',
            'edit-branches',
            'delete-branches',
            'toggle-status-branches',

            // Cash register management permissions
            'manage-cash-registers',
            'view-cash-registers',
            'create-cash-registers',
            'edit-cash-registers',
            'delete-cash-registers',
            'toggle-status-cash-registers',

            // POS session management permissions
            'manage-pos-sessions',
            'view-pos-sessions',
            'create-pos-sessions',
            'close-pos-sessions',
            'edit-pos-sessions',
            'delete-pos-sessions',
            'manage-any-pos-sessions',

            // Purchase Orders
            'manage-purchase-orders',
            'view-purchase-orders',
            'create-purchase-orders',
            'edit-purchase-orders',
            'delete-purchase-orders',
            'toggle-status-purchase-orders',

            // Role management permissions
            'manage-roles',
            'create-roles',
            'edit-roles',
            'delete-roles',
            'view-roles',
            'view-permissions',
            'manage-plans',
            'view-plans',
            'manage-plan-requests',
            'manage-plan-orders',
            'view-plan-orders',
            'request-plans',
            'trial-plans',
            'subscribe-plans',
            'manage-referral',
            'manage-users-referral',
            'manage-setting-referral',
            'manage-payout-referral',
            'approve-payout-referral',
            'reject-payout-referral',
            'manage-email-settings',
            'manage-brand-settings',
            'manage-webhook-settings',
            'manage-settings',
            'manage-media',
            'manage-own-media',
            'create-media',
            'edit-media',
            'delete-media',
            'view-media',
            'download-media',
            'manage-calendar',
            'view-calendar',
            'manage-language',
            'edit-language',
            'view-language',
            'view-landing-page',
            'manage-analytics',
            'manage-taxes',
            'view-taxes',
            'create-taxes',
            'edit-taxes',
            'delete-taxes',
            'toggle-status-taxes',
            'manage-brands',
            'view-brands',
            'create-brands',
            'edit-brands',
            'delete-brands',
            'toggle-status-brands',
            'manage-units',
            'view-units',
            'create-units',
            'edit-units',
            'delete-units',
            'toggle-status-units',
            'manage-categories',
            'view-categories',
            'create-categories',
            'edit-categories',
            'delete-categories',
            'toggle-status-categories',
            'manage-generic-names',
            'view-generic-names',
            'create-generic-names',
            'edit-generic-names',
            'delete-generic-names',
            'toggle-status-generic-names',
            'manage-drug-forms',
            'view-drug-forms',
            'create-drug-forms',
            'edit-drug-forms',
            'delete-drug-forms',
            'toggle-status-drug-forms',
            'manage-products',
            'view-products',
            'create-products',
            'edit-products',
            'delete-products',
            'toggle-status-products',
            'manage-account-types',
            'view-account-types',
            'create-account-types',
            'edit-account-types',
            'delete-account-types',
            'toggle-status-account-types',
            'manage-account-industries',
            'view-account-industries',
            'create-account-industries',
            'edit-account-industries',
            'delete-account-industries',
            'toggle-status-account-industries',
            'manage-accounts',
            'view-accounts',
            'create-accounts',
            'edit-accounts',
            'delete-accounts',
            'toggle-status-accounts',
            'manage-customers',
            'view-customers',
            'create-customers',
            'edit-customers',
            'delete-customers',
            'manage-contacts',
            'view-contacts',
            'create-contacts',
            'edit-contacts',
            'delete-contacts',
            'toggle-status-contacts',
            'manage-lead-statuses',
            'view-lead-statuses',
            'create-lead-statuses',
            'edit-lead-statuses',
            'delete-lead-statuses',
            'toggle-status-lead-statuses',
            'manage-lead-sources',
            'view-lead-sources',
            'create-lead-sources',
            'edit-lead-sources',
            'delete-lead-sources',
            'toggle-status-lead-sources',
            'manage-leads',
            'view-leads',
            'create-leads',
            'edit-leads',
            'delete-leads',
            'toggle-status-leads',
            'convert-leads',
            'manage-opportunity-stages',
            'view-opportunity-stages',
            'create-opportunity-stages',
            'edit-opportunity-stages',
            'delete-opportunity-stages',
            'toggle-status-opportunity-stages',
            'manage-opportunity-sources',
            'view-opportunity-sources',
            'create-opportunity-sources',
            'edit-opportunity-sources',
            'delete-opportunity-sources',
            'toggle-status-opportunity-sources',
            'manage-opportunities',
            'view-opportunities',
            'create-opportunities',
            'edit-opportunities',
            'delete-opportunities',
            'toggle-status-opportunities',
            'manage-campaign-types',
            'view-campaign-types',
            'create-campaign-types',
            'edit-campaign-types',
            'delete-campaign-types',
            'toggle-status-campaign-types',
            'manage-target-lists',
            'view-target-lists',
            'create-target-lists',
            'edit-target-lists',
            'delete-target-lists',
            'toggle-status-target-lists',
            'manage-campaigns',
            'view-campaigns',
            'create-campaigns',
            'edit-campaigns',
            'delete-campaigns',
            'toggle-status-campaigns',
            'manage-shipping-provider-types',
            'view-shipping-provider-types',
            'create-shipping-provider-types',
            'edit-shipping-provider-types',
            'delete-shipping-provider-types',
            'toggle-status-shipping-provider-types',

            'manage-cases',
            'view-cases',
            'create-cases',
            'edit-cases',
            'delete-cases',
            'toggle-status-cases',
            'manage-quotes',
            'view-quotes',
            'create-quotes',
            'edit-quotes',
            'delete-quotes',
            'toggle-status-quotes',
            'manage-sales-orders',
            'view-sales-orders',
            'create-sales-orders',
            'edit-sales-orders',
            'delete-sales-orders',
            'toggle-status-sales-orders',
            'manage-invoices',
            'view-invoices',
            'create-invoices',
            'edit-invoices',
            'delete-invoices',
            'toggle-status-invoices',
            'manage-delivery-orders',
            'view-delivery-orders',
            'create-delivery-orders',
            'edit-delivery-orders',
            'delete-delivery-orders',
            'toggle-status-delivery-orders',
            'manage-delivery-routes',
            'view-delivery-routes',
            'create-delivery-routes',
            'edit-delivery-routes',
            'delete-delivery-routes',
            'toggle-status-delivery-routes',
            'view-return-orders',
            'create-return-orders',
            'edit-return-orders',
            'delete-return-orders',
            'manage-purchase-orders',
            'view-purchase-orders',
            'create-purchase-orders',
            'edit-purchase-orders',
            'delete-purchase-orders',
            'toggle-status-purchase-orders',
            'manage-receipt-orders',
            'view-receipt-orders',
            'create-receipt-orders',
            'edit-receipt-orders',
            'delete-receipt-orders',
            'toggle-status-receipt-orders',
            'manage-projects',
            'view-projects',
            'create-projects',
            'edit-projects',
            'delete-projects',
            'toggle-status-projects',
            'manage-project-tasks',
            'view-project-tasks',
            'create-project-tasks',
            'edit-project-tasks',
            'delete-project-tasks',
            'toggle-status-project-tasks',
            'manage-task-statuses',
            'view-task-statuses',
            'create-task-statuses',
            'edit-task-statuses',
            'delete-task-statuses',
            'toggle-status-task-statuses',
            'manage-meetings',
            'view-meetings',
            'create-meetings',
            'edit-meetings',
            'delete-meetings',
            'toggle-status-meetings',
            'manage-calls',
            'view-calls',
            'create-calls',
            'edit-calls',
            'delete-calls',
            'toggle-status-calls',
            'manage-document-folders',
            'view-document-folders',
            'create-document-folders',
            'edit-document-folders',
            'delete-document-folders',
            'toggle-status-document-folders',
            'manage-document-types',
            'view-document-types',
            'create-document-types',
            'edit-document-types',
            'delete-document-types',
            'toggle-status-document-types',
            'manage-documents',
            'view-documents',
            'create-documents',
            'edit-documents',
            'delete-documents',
            'toggle-status-documents',
            'manage-reports',
            'view-lead-reports',
            'view-sales-reports',
            'view-product-reports',
            'view-customer-reports',
            'view-customer-details-report',
            'view-supplier-details-report',
            'view-supplier-ledger-card',
            'view-customer-ledger-card',
            'view-price-details-report',
            'view-cash-collection-report',
            'view-project-reports',
            'manage-notification-templates',
            'view-notification-templates',
            'create-notification-templates',
            'edit-notification-templates',
            'delete-notification-templates',
            'manage-finance',
            'manage-inventory',
            'view-inventory-transactions',
            'view-inventory-dashboard',
            'view-inventory-audit',
            'view-drug-destroys',
            'create-drug-destroys',
            'manage-prescriptions',
            'manage-customer-payments',
            'view-customer-payments',
            'create-customer-payments',
            'view-customer-returns',
            'create-customer-returns',
            'manage-grns',
            'view-grns',
            // Sales Module
            'manage-sales',
            'view-sales',
            'create-sales',
            'edit-completed-sales',
            'edit-sales',
            'delete-sales',
            'toggle-status-sales',
            'manage-points-earning-rules',
        ])->get();

        $adminRole->syncPermissions($adminPermissions);
    }
}
